# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target='sharding_client',
    source=[
        'shard_remote.cpp',
         env.Idlc('shard_remote.idl')[0],
    ],
    LIBDEPS=[
        '$BUILD_DIR/monger/client/fetcher',
        '$BUILD_DIR/monger/db/commands',
        '$BUILD_DIR/monger/db/lasterror',
        '$BUILD_DIR/monger/executor/task_executor_pool',
        '$BUILD_DIR/monger/s/grid',
        'shard_interface',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/monger/idl/server_parameter',
    ],
)

env.Library(
    target='shard_interface',
    source=[
        'shard.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/monger/base',
        '$BUILD_DIR/monger/client/remote_command_retry_scheduler',
        '$BUILD_DIR/monger/s/common_s',
        '$BUILD_DIR/monger/s/write_ops/batch_write_types',
    ],
)

env.Library(
    target='rs_local_client',
    source=[
        'rs_local_client.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/monger/client/clientdriver_minimal',
        '$BUILD_DIR/monger/db/dbdirectclient',
        '$BUILD_DIR/monger/db/repl/repl_coordinator_interface',
    ],
)

env.Library(
    target='shard_local',
    source=[
        'shard_local.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/monger/client/clientdriver_minimal',
        '$BUILD_DIR/monger/db/repl/repl_coordinator_interface',
        'rs_local_client',
        'shard_interface',
    ],
)

env.CppUnitTest(
    target='mongers_client_test',
    source=[
        'shard_registry_data_test.cpp',
        'shard_remote_test.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/monger/s/coreshard',
        '$BUILD_DIR/monger/s/query/async_results_merger',
        '$BUILD_DIR/monger/s/sharding_router_test_fixture',
        'sharding_client',
    ],
)

# The shard local test globally sets server options into the config
# server state, which is incompatible with the other tests.
env.CppUnitTest(
    target='mongers_client_local_test',
    source=[
        'shard_local_test.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/monger/db/auth/authmocks',
        '$BUILD_DIR/monger/db/repl/replmocks',
        '$BUILD_DIR/monger/db/service_context_d_test_fixture',
        '$BUILD_DIR/monger/s/grid',
        'shard_local',
    ],
)
