Import("env")

env = env.Clone()

sorterEnv = env.Clone()
sorterEnv.InjectThirdParty(libraries=['snappy'])

sorterEnv.CppUnitTest(
    target='db_sorter_test',
    source=[
        'sorter_test.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/monger/db/service_context',
        '$BUILD_DIR/monger/db/service_context_test_fixture',
        '$BUILD_DIR/monger/db/storage/encryption_hooks',
        '$BUILD_DIR/monger/db/storage/storage_options',
        '$BUILD_DIR/monger/s/is_mongers',
        '$BUILD_DIR/third_party/shim_snappy'
    ],
)
