# -*- mode: python -*-

Import('env')

env.Library(
    target='watchdog',
    source=[
        'watchdog.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/monger/base',
        '$BUILD_DIR/monger/db/service_context',
        '$BUILD_DIR/monger/db/storage/storage_options',
    ]
)

env.Library(
    target='watchdog_register',
    source=[
        'watchdog_register.cpp',
    ],
)

env.Library(
    target='watchdog_mongerd',
    source=[
        'watchdog_mongerd.cpp',
        env.Idlc('watchdog_mongerd.idl')[0],
    ],
    LIBDEPS=[
        '$BUILD_DIR/monger/db/commands/server_status',
        'watchdog',
        ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/monger/db/server_options_core',
        '$BUILD_DIR/monger/idl/server_parameter',
        'watchdog_register',
        ],
)

env.CppUnitTest(
    target='watchdog_test',
    source=[
        'watchdog_test.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/monger/db/service_context_test_fixture',
        '$BUILD_DIR/monger/util/clock_source_mock',
        'watchdog',
    ],
)
