# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target='views_mongerd',
    source=[
        'durable_view_catalog.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/monger/db/dbhelpers',
        '$BUILD_DIR/monger/db/views/views',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/monger/db/catalog/database_holder',
    ],
)

env.Library(
    target='views',
    source=[
        'view.cpp',
        'view_catalog.cpp',
        'view_graph.cpp',
    ],
    LIBDEPS=[
        'resolved_view',
        '$BUILD_DIR/monger/base',
        '$BUILD_DIR/monger/db/pipeline/aggregation',
        '$BUILD_DIR/monger/db/repl/repl_coordinator_interface',
        '$BUILD_DIR/monger/db/query/collation/collator_factory_interface',
    ]
)

env.Library(
    target='resolved_view',
    source=[
        'resolved_view.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/monger/base',
    ]
)

env.CppUnitTest(
    target='db_views_test',
    source=[
        'resolved_view_test.cpp',
        'view_catalog_test.cpp',
        'view_definition_test.cpp',
        'view_graph_test.cpp',
    ],
    LIBDEPS=[
        'views',
        '$BUILD_DIR/monger/db/auth/authmocks',
        '$BUILD_DIR/monger/db/query/collation/collator_interface_mock',
        '$BUILD_DIR/monger/db/query/query_test_service_context',
        '$BUILD_DIR/monger/db/repl/replmocks',
        '$BUILD_DIR/monger/s/is_mongers',
        '$BUILD_DIR/monger/unittest/unittest',
    ],
)
