services:
  notary_url: "http://notary-service.build.10gen.cc:5000"

templates:
  deb:
    org: |
      Origin: mongerdb
      Label: mongerdb
      Suite: {{ .CodeName }}
      Codename: {{ .CodeName }}/mongerdb-org
      Architectures: {{ .Architectures }}
      Components: {{ .Component }}
      Description: MongoDB packages
    enterprise: |
      Origin: mongerdb
      Label: mongerdb
      Suite: {{ .CodeName }}
      Codename: {{ .CodeName }}/mongerdb-enterprise
      Architectures: {{ .Architectures }}
      Components: {{ .Component }}
      Description: MongoDB packages
  index_page: |
    <!DOCTYPE html>
    <html>
     <head>
       <title>{{ .Title }}</title>
     </head>

     <body>
       <table>
        <tr><td>
          <h1>{{ .Title }}</h1>
        </td></tr>

        <tr><td>
          <hr>
        </td></tr>

        <tr><td>
          <a href='..'>Parent Directory</a>
        </td></tr>

        {{ range $fn := .Files }}
        <tr><td>
          <a href='{{ $fn }}'>{{ $fn }}</a>
        </td></tr>
        {{ end }}

        <tr><td>
          <hr>
        </td></tr>

        <tr><td>
          <address>{{ .RepoName }}</address>
        </td></tr>
      </table>
     </body>
    </html>


repos:

####################
#
# Community Repos:
#
####################

  - name: rhel62
    type: rpm
    edition: org
    bucket: repo.mongerdb.org
    repos:
      - yum/redhat/6/mongerdb-org
      - yum/redhat/6Server/mongerdb-org

  - name: rhel67
    type: rpm
    edition: org
    bucket: repo.mongerdb.org
    repos:
      - yum/redhat/6/mongerdb-org
      - yum/redhat/6Server/mongerdb-org

  - name: rhel70
    type: rpm
    edition: org
    bucket: repo.mongerdb.org
    repos:
      - yum/redhat/7/mongerdb-org
      - yum/redhat/7Server/mongerdb-org

  - name: rhel72
    type: rpm
    edition: org
    bucket: repo.mongerdb.org
    repos:
      - yum/redhat/7/mongerdb-org
      - yum/redhat/7Server/mongerdb-org

  - name: amazon
    type: rpm
    edition: org
    bucket: repo.mongerdb.org
    repos:
      - yum/amazon/2013.03/mongerdb-org

  - name: amazon2
    type: rpm
    edition: org
    bucket: repo.mongerdb.org
    repos:
      - yum/amazon/2/mongerdb-org

  - name: suse11
    type: rpm
    edition: org
    bucket: repo.mongerdb.org
    repos:
      - zypper/suse/11/mongerdb-org

  - name: suse12
    type: rpm
    edition: org
    bucket: repo.mongerdb.org
    repos:
      - zypper/suse/12/mongerdb-org

  - name: suse15
    type: rpm
    edition: org
    bucket: repo.mongerdb.org
    repos:
      - zypper/suse/15/mongerdb-org

  - name: debian81
    type: deb
    code_name: "jessie"
    bucket: repo.mongerdb.org
    edition: org
    component: main
    architectures:
      - amd64
      - i386
    repos:
      - apt/debian/dists/jessie/mongerdb-org

  - name: debian92
    type: deb
    code_name: "stretch"
    bucket: repo.mongerdb.org
    edition: org
    component: main
    architectures:
      - amd64
    repos:
      - apt/debian/dists/stretch/mongerdb-org

  - name: debian71
    type: deb
    code_name: "wheezy"
    bucket: repo.mongerdb.org
    edition: org
    component: main
    architectures:
      - amd64
      - i386
    repos:
      - apt/debian/dists/wheezy/mongerdb-org

  - name: ubuntu1204
    type: deb
    code_name: "precise"
    edition: org
    bucket: repo.mongerdb.org
    component: multiverse
    architectures:
      - amd64
      - i386
    repos:
      - apt/ubuntu/dists/precise/mongerdb-org

  - name: ubuntu1404
    type: deb
    code_name: "trusty"
    edition: org
    bucket: repo.mongerdb.org
    component: multiverse
    architectures:
      - amd64
      - i386
    repos:
      - apt/ubuntu/dists/trusty/mongerdb-org

  - name: ubuntu1604
    type: deb
    code_name: "xenial"
    edition: org
    bucket: repo.mongerdb.org
    component: multiverse
    architectures:
      - amd64
      - arm64
      - i386
    repos:
      - apt/ubuntu/dists/xenial/mongerdb-org

  - name: ubuntu1804
    type: deb
    code_name: "bionic"
    edition: org
    bucket: repo.mongerdb.org
    component: multiverse
    architectures:
      - amd64
      - i386
      - s390x
      - arm64
    repos:
      - apt/ubuntu/dists/bionic/mongerdb-org

####################
#
# Enterprise Repos:
#
####################

  - name: rhel62
    type: rpm
    edition: enterprise
    bucket: repo.mongerdb.com
    repos:
      - yum/redhat/6/mongerdb-enterprise
      - yum/redhat/6Server/mongerdb-enterprise

  - name: rhel67
    type: rpm
    edition: enterprise
    bucket: repo.mongerdb.com
    repos:
      - yum/redhat/6/mongerdb-enterprise
      - yum/redhat/6Server/mongerdb-enterprise

  - name: rhel70
    type: rpm
    edition: enterprise
    bucket: repo.mongerdb.com
    repos:
      - yum/redhat/7/mongerdb-enterprise
      - yum/redhat/7Server/mongerdb-enterprise

  - name: rhel71
    type: rpm
    edition: enterprise
    bucket: repo.mongerdb.com
    repos:
      - yum/redhat/7/mongerdb-enterprise
      - yum/redhat/7Server/mongerdb-enterprise

  - name: rhel72
    type: rpm
    edition: enterprise
    bucket: repo.mongerdb.com
    repos:
      - yum/redhat/7/mongerdb-enterprise
      - yum/redhat/7Server/mongerdb-enterprise

  - name: amazon
    type: rpm
    edition: enterprise
    bucket: repo.mongerdb.com
    repos:
      - yum/amazon/2013.03/mongerdb-enterprise

  - name: amazon2
    type: rpm
    edition: enterprise
    bucket: repo.mongerdb.com
    repos:
      - yum/amazon/2/mongerdb-enterprise

  - name: suse11
    type: rpm
    edition: enterprise
    bucket: repo.mongerdb.com
    repos:
      - zypper/suse/11/mongerdb-enterprise

  - name: suse12
    type: rpm
    edition: enterprise
    bucket: repo.mongerdb.com
    repos:
      - zypper/suse/12/mongerdb-enterprise

  - name: suse15
    type: rpm
    edition: enterprise
    bucket: repo.mongerdb.com
    repos:
      - zypper/suse/15/mongerdb-enterprise

  - name: debian92
    type: deb
    edition: enterprise
    code_name: "stretch"
    bucket: repo.mongerdb.com
    component: main
    architectures:
      - amd64
    repos:
      - apt/debian/dists/stretch/mongerdb-enterprise

  - name: debian81
    type: deb
    edition: enterprise
    code_name: "jessie"
    bucket: repo.mongerdb.com
    component: main
    architectures:
      - amd64
      - ppc64el
      - s390x
      - i386
    repos:
      - apt/debian/dists/jessie/mongerdb-enterprise

  - name: debian71
    type: deb
    code_name: "wheezy"
    edition: enterprise
    bucket: repo.mongerdb.com
    component: main
    architectures:
      - amd64
      - ppc64el
      - s390x
      - i386
    repos:
      - apt/debian/dists/wheezy/mongerdb-enterprise

  - name: ubuntu1204
    type: deb
    code_name: "precise"
    edition: enterprise
    bucket: repo.mongerdb.com
    component: multiverse
    architectures:
      - amd64
      - ppc64el
      - s390x
      - i386
    repos:
      - apt/ubuntu/dists/precise/mongerdb-enterprise

  - name: ubuntu1404
    type: deb
    code_name: "trusty"
    edition: enterprise
    bucket: repo.mongerdb.com
    component: multiverse
    architectures:
      - amd64
      - ppc64el
      - s390x
      - i386
    repos:
      - apt/ubuntu/dists/trusty/mongerdb-enterprise

  - name: ubuntu1604
    type: deb
    code_name: "xenial"
    edition: enterprise
    bucket: repo.mongerdb.com
    component: multiverse
    architectures:
      - amd64
      - ppc64el
      - s390x
      - arm64
      - i386
    repos:
      - apt/ubuntu/dists/xenial/mongerdb-enterprise

  - name: ubuntu1804
    type: deb
    code_name: "bionic"
    edition: enterprise
    bucket: repo.mongerdb.com
    component: multiverse
    architectures:
      - amd64
      - ppc64el
      - i386
      - s390x
      - arm64
    repos:
      - apt/ubuntu/dists/bionic/mongerdb-enterprise
