# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target='write_ops_exec',
    source=[
        'write_ops_exec.cpp',
        ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/monger/base',
        '$BUILD_DIR/monger/db/catalog_raii',
        '$BUILD_DIR/monger/db/catalog/collection_options',
        '$BUILD_DIR/monger/db/curop',
        '$BUILD_DIR/monger/db/curop_metrics',
        '$BUILD_DIR/monger/db/repl/oplog',
        '$BUILD_DIR/monger/db/repl/repl_coordinator_interface',
        '$BUILD_DIR/monger/db/stats/counters',
        '$BUILD_DIR/monger/db/stats/server_read_concern_write_concern_metrics',
        '$BUILD_DIR/monger/db/transaction',
        '$BUILD_DIR/monger/db/write_ops',
        '$BUILD_DIR/monger/util/fail_point',
        '$BUILD_DIR/monger/util/log_and_backoff',
    ],
)

env.Library(
    target='write_ops_parsers',
    source=[
        'write_ops_parsers.cpp',
        env.Idlc('write_ops.idl')[0],
    ],
    LIBDEPS=[
        '$BUILD_DIR/monger/base',
        '$BUILD_DIR/monger/db/commands/test_commands_enabled',
        '$BUILD_DIR/monger/db/dbmessage',
        '$BUILD_DIR/monger/db/pipeline/runtime_constants_idl',
        '$BUILD_DIR/monger/db/query/hint_parser',
        '$BUILD_DIR/monger/idl/idl_parser',
    ],
)

env.Library(
    target='write_ops_parsers_test_helpers',
    source=[
        'write_ops_parsers_test_helpers.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/monger/base',
        '$BUILD_DIR/monger/db/dbmessage',
    ],
)

env.Library(
    target='parsed_update',
    source='parsed_update.cpp',
    LIBDEPS=[
        '$BUILD_DIR/monger/base',
        '$BUILD_DIR/monger/db/update/update_driver',
    ],
)

env.CppUnitTest(
    target='db_ops_test',
    source=[
        'write_ops_parsers_test.cpp',
        'write_ops_retryability_test.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/monger/db/auth/authmocks',
        '$BUILD_DIR/monger/db/query_exec',
        '$BUILD_DIR/monger/db/repl/mock_repl_coord_server_fixture',
        '$BUILD_DIR/monger/db/repl/oplog_entry',
        '$BUILD_DIR/monger/db/write_ops',
        'write_ops_parsers',
        'write_ops_parsers_test_helpers',
    ],
)

env.CppIntegrationTest(
    target='db_ops_integration_test',
    source='write_ops_document_stream_integration_test.cpp',
    LIBDEPS=[
        '$BUILD_DIR/monger/client/clientdriver_network',
        '$BUILD_DIR/monger/transport/transport_layer_egress_init',
        '$BUILD_DIR/monger/util/version_impl',
    ],
)
