# -*- mode: python; -*-

Import('env')

env = env.Clone()

env.SConscript(
    dirs=[
        'mutable',
        'util',
    ],
    exports=[
        'env',
    ],
)

env.CppUnitTest(
    target='bson_test',
    source=[
        'bson_field_test.cpp',
        'bson_obj_data_type_test.cpp',
        'bson_obj_test.cpp',
        'bson_validate_test.cpp',
        'bsonelement_test.cpp',
        'bsonobjbuilder_test.cpp',
        'oid_test.cpp',
        'simple_bsonobj_comparator_test.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/monger/base',
    ],
)

env.Benchmark(
    target='bsonobjbuilder_bm',
    source=[
        'bsonobjbuilder_bm.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/monger/base',
    ],
)

env.CppLibfuzzerTest(
    target='bson_validate_fuzzer',
    source=[
        'bson_validate_fuzzer.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/monger/base',
    ],
)

asioEnv = env.Clone()
asioEnv.InjectThirdParty('asio')

asioEnv.CppIntegrationTest(
    target='bson_integration_test',
    source=[
        'ugly_bson_integration_test.cpp'
    ],
    LIBDEPS=[
        '$BUILD_DIR/monger/executor/network_interface_fixture',
        '$BUILD_DIR/monger/rpc/protocol',
        '$BUILD_DIR/monger/transport/transport_layer_egress_init',
    ],
)
