# -*- mode: python -*-
Import("env")

env = env.Clone()

env.Library(
    target= 'ephemeral_for_test_record_store',
    source= [
        'ephemeral_for_test_record_store.cpp'
        ],
    LIBDEPS= [
        '$BUILD_DIR/monger/base',
        '$BUILD_DIR/monger/db/concurrency/lock_manager',
        '$BUILD_DIR/monger/db/storage/oplog_hack',
        ]
    )

env.Library(
    target= 'storage_ephemeral_for_test_core',
    source= [
        'ephemeral_for_test_btree_impl.cpp',
        'ephemeral_for_test_engine.cpp',
        'ephemeral_for_test_recovery_unit.cpp',
        ],
    LIBDEPS= [
        'ephemeral_for_test_record_store',
        '$BUILD_DIR/monger/base',
        '$BUILD_DIR/monger/db/namespace_string',
        '$BUILD_DIR/monger/db/catalog/collection_options',
        '$BUILD_DIR/monger/db/index/index_descriptor',
        '$BUILD_DIR/monger/db/repl/repl_coordinator_interface',
        '$BUILD_DIR/monger/db/storage/index_entry_comparison',
        '$BUILD_DIR/monger/db/storage/journal_listener',
        '$BUILD_DIR/monger/db/storage/recovery_unit_base',
        '$BUILD_DIR/monger/db/storage/kv/kv_prefix',
        ]
    )

env.Library(
    target= 'storage_ephemeral_for_test',
    source= [
        'ephemeral_for_test_init.cpp',
    ],
    LIBDEPS= [
        'storage_ephemeral_for_test_core',
        '$BUILD_DIR/monger/db/storage/durable_catalog_impl',
        '$BUILD_DIR/monger/db/storage/storage_engine_impl',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/monger/db/storage/storage_engine_common',
    ],
)

env.CppUnitTest(
   target='storage_ephemeral_for_test_btree_test',
   source=['ephemeral_for_test_btree_impl_test.cpp'
           ],
   LIBDEPS=[
        'storage_ephemeral_for_test_core',
        '$BUILD_DIR/monger/db/storage/sorted_data_interface_test_harness'
        ]
   )

env.CppUnitTest(
   target='storage_ephemeral_for_test_record_store_test',
   source=['ephemeral_for_test_record_store_test.cpp'
           ],
   LIBDEPS=[
        'storage_ephemeral_for_test_core',
        '$BUILD_DIR/monger/db/storage/record_store_test_harness'
        ]
   )

env.CppUnitTest(
    target='storage_ephemeral_for_test_engine_test',
    source=['ephemeral_for_test_engine_test.cpp',
            ],
    LIBDEPS=[
        '$BUILD_DIR/monger/db/storage/kv/kv_engine_test_harness',
        '$BUILD_DIR/monger/db/storage/storage_options',
        'storage_ephemeral_for_test_core',
        ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/monger/db/auth/authmocks',
    ],
)
